language: python
python:
  - "2.7"

install:
- pip install -r requirements/requirements.txt
- pip install -r requirements/requirements-ci.txt

script:
- ./scripts/test.sh

after_success:
- coveralls debug
